"""CDK Stack for RAJA web interface."""

from __future__ import annotations

from pathlib import Path

from aws_cdk import Stack
from constructs import Construct

from ..constructs.static_site import StaticSite


class WebStack(Stack):
    """Stack for deploying the RAJA web demo interface.

    This stack creates:
    - S3 bucket with static website files
    - CloudFront distribution for HTTPS access
    - Automatic injection of API Gateway URL into frontend config
    """

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        api_url: str,
        **kwargs: object,
    ) -> None:
        """Initialize the WebStack.

        Args:
            scope: CDK construct scope
            construct_id: Stack identifier
            api_url: API Gateway URL from ServicesStack
            **kwargs: Additional keyword arguments
        """
        super().__init__(scope, construct_id, **kwargs)

        # Get path to web directory (relative to this file)
        repo_root = Path(__file__).parent.parent.parent.parent
        web_path = str(repo_root / "web")

        # Generate config.js content with API URL
        config_content = self._generate_config(api_url)

        # Create static site with CloudFront
        static_site = StaticSite(
            self,
            "RajaWebSite",
            site_path=web_path,
            config_content=config_content,
        )

        # Store reference
        self.website_url = static_site.url

    def _generate_config(self, api_url: str) -> str:
        """Generate config.js content with API URL.

        Args:
            api_url: API Gateway URL

        Returns:
            JavaScript config file content
        """
        # Remove trailing slash if present
        api_url = api_url.rstrip("/")

        return f"""// RAJA Configuration
// Auto-generated by CDK deployment

window.RAJA_CONFIG = {{
    apiUrl: '{api_url}'
}};
"""
