version: 1
default_project: alpha
projects:
  - key: alpha
    display_name: Alpha
    project_name: alpha
    designation: PROJECT_CONTRIBUTOR
    buckets: "*"
  - key: bio
    display_name: Bio
    project_name: bio
    designation: PROJECT_CONTRIBUTOR
    buckets: "*bio*"
  - key: compute
    display_name: Compute
    project_name: compute
    designation: PROJECT_CONTRIBUTOR
    buckets: "*example*"
packages:
  - name: alpha/home
    producer_project: alpha
    consumer_project: bio
  - name: bio/home
    producer_project: bio
    consumer_project: compute
  - name: compute/home
    producer_project: compute
    consumer_project: alpha
