.PHONY: html

html:
	@mkdir -p _build/html
	@printf '%s\n' '<!doctype html><html><head><meta charset="utf-8"><title>RAJA Docs</title></head><body><h1>RAJA Docs</h1><p>Placeholder documentation.</p></body></html>' > _build/html/index.html
